from django.conf.urls import url 
from . import views 

from django.urls import path
from rest_framework.authtoken import views as rfa_views

 
urlpatterns = [
    # template views
    path('',views.home, name='home'),
    path('farmers/',views.farmers, name='farmers'),
    path('print_farmers', views.print_farmers, name="print_farmers"),


    # api views
    path('api/token/', rfa_views.obtain_auth_token, name="api-token-auth"),
    path('kilosahihi/api/users', views.users_list),
    path('kilosahihi/api/users/<int:pk>/', views.users_detail),
    path('kilosahihi/api/users/active', views.users_list_active),
    path('kilosahihi/api/user_permissions', views.userpermissions_list),
    path('kilosahihi/api/user_permissions/<int:pk>/', views.userpermissions_detail),
    path('kilosahihi/api/user_permissions/active', views.userpermissions_list_active),
    path('kilosahihi/api/user_roles', views.userroles_list),
    path('kilosahihi/api/user_roles/<int:pk>/', views.userroles_detail),
    path('kilosahihi/api/user_roles/active', views.userroles_list_active),
    path('kilosahihi/api/user_attributes', views.userattributes_list),
    path('kilosahihi/api/user_attributes/<int:pk>/', views.userattributes_detail),
    path('kilosahihi/api/user_attributes/active', views.userattributes_list_active),
    path('kilosahihi/api/audits', views.audits_list),
    path('kilosahihi/api/audits/<int:pk>/', views.audits_detail),
    path('kilosahihi/api/audits/active', views.audits_list_active),
    path('kilosahihi/api/banks', views.banks_list),
    path('kilosahihi/api/banks/<int:pk>/', views.banks_detail),
    path('kilosahihi/api/banks/active', views.banks_list_active),
    path('kilosahihi/api/userbankaccounts', views.userbankaccounts_list),
    path('kilosahihi/api/userbankaccounts/<int:pk>/', views.userbankaccounts_detail),
    path('kilosahihi/api/userbankaccounts/active', views.userbankaccounts_list_active),
    path('kilosahihi/api/unions', views.unions_list),
    path('kilosahihi/api/unions/<int:pk>/', views.unions_detail),
    path('kilosahihi/api/unions/active', views.unions_list_active),
    path('kilosahihi/api/unionsusers', views.userunions_list),
    path('kilosahihi/api/unionsusers/<int:pk>/', views.userunions_detail),
    path('kilosahihi/api/unionsusers/active', views.userunions_list_active),
    path('kilosahihi/api/cooperatives', views.cooperatives_list),
    path('kilosahihi/api/cooperatives/<int:pk>/', views.cooperatives_detail),
    path('kilosahihi/api/cooperatives/active', views.cooperatives_list_active),
    path('kilosahihi/api/cooperativesusers', views.usercooperatives_list),
    path('kilosahihi/api/cooperativesusers/<int:pk>/', views.usercooperatives_detail),
    path('kilosahihi/api/cooperativesusers/active', views.usercooperatives_list_active),
    path('kilosahihi/api/produce', views.produce_list),
    path('kilosahihi/api/produce/<int:pk>/', views.produce_detail),
    path('kilosahihi/api/produce/active', views.produce_list_active),
    path('kilosahihi/api/factories', views.factories_list),
    path('kilosahihi/api/factories/<int:pk>/', views.factories_detail),
    path('kilosahihi/api/factories/active', views.factories_list_active),
    path('kilosahihi/api/devices', views.devices_list),
    path('kilosahihi/api/devices/<int:pk>/', views.devices_detail),
    path('kilosahihi/api/devices/active', views.devices_list_active),
    path('kilosahihi/api/smallholderestates', views.smallholderestates_list),
    path('kilosahihi/api/smallholderestates/<int:pk>/', views.smallholderestates_detail),
    path('kilosahihi/api/smallholderestates/active', views.smallholderestates_list_active),
    path('kilosahihi/api/smallholderestatesusers', views.usersmallholderestates_list),
    path('kilosahihi/api/smallholderestatesusers/<int:pk>/', views.usersmallholderestates_detail),
    path('kilosahihi/api/smallholderestatesusers/active', views.usersmallholderestates_list_active),
    path('kilosahihi/api/smallholderestates/transactions', views.smallholderestatestransactions_list),
    path('kilosahihi/api/smallholderestates/transactions/<int:pk>/', views.smallholderestatestransactions_detail),
    path('kilosahihi/api/smallholderestates/transactions/active', views.smallholderestatestransactions_list_active),
    path('kilosahihi/api/fieldofficers', views.userfieldofficers_list),
    path('kilosahihi/api/fieldofficers/<int:pk>/', views.userfieldofficers_detail),
    path('kilosahihi/api/fieldofficers/active', views.userfieldofficers_list_active),
    path('kilosahihi/api/farmers', views.userfarmers_list),
    path('kilosahihi/api/farmers/<int:pk>/', views.userfarmers_detail),
    path('kilosahihi/api/farmers/active', views.userfarmers_list_active),
    path('kilosahihi/api/farmers/username/<int:pk>/', views.userfarmers_username),#########
    path('kilosahihi/api/farms', views.farms_list),
    path('kilosahihi/api/farms/<int:pk>/', views.farms_detail),
    path('kilosahihi/api/farms/active', views.farms_list_active),
    path('kilosahihi/api/farmers/transactions', views.farmerstransactions_list),
    path('kilosahihi/api/farmers/transactions/<int:pk>/', views.farmerstransactions_detail),
    path('kilosahihi/api/farmers/transactions/active', views.farmerstransactions_list_active),
    path('kilosahihi/api/farmerincomesource/transactions', views.farmerincomesource_list),
    path('kilosahihi/api/farmerincomesource/<int:pk>/', views.farmerincomesource_detail),
    path('kilosahihi/api/farmerincomesource/active', views.farmerincomesource_list_active),
    path('kilosahihi/api/farmerdebts', views.farmerincomesource_list),
    path('kilosahihi/api/farmerdebts/<int:pk>/', views.farmerincomesource_detail),
    path('kilosahihi/api/farmerdebts/active', views.farmerincomesource_list_active),
    path('kilosahihi/api/smallholderestateincomesource', views.smallholderestateincomesource_list),
    path('kilosahihi/api/smallholderestateincomesource/<int:pk>/', views.smallholderestateincomesource_detail),
    path('kilosahihi/api/smallholderestateincomesource/active', views.smallholderestateincomesource_list_active),
    path('kilosahihi/api/smallholderestatedebts', views.smallholderestatedebts_list),
    path('kilosahihi/api/smallholderestatedebts/<int:pk>/', views.smallholderestatedebts_detail),
    path('kilosahihi/api/smallholderestatedebts/active', views.smallholderestatedebts_list_active),
    path('kilosahihi/api/smallholderestateinputrequest', views.smallholderestateinputrequest_list),
    path('kilosahihi/api/smallholderestateinputrequest/<int:pk>/', views.smallholderestateinputrequest_detail),
    path('kilosahihi/api/smallholderestateinputrequest/active', views.smallholderestateinputrequest_list_active),
    path('kilosahihi/api/payment', views.payment_list),
    path('kilosahihi/api/payment/<int:pk>/', views.payment_detail),
    path('kilosahihi/api/payment/active', views.payment_list_active),
    path('kilosahihi/api/farmerinputrequest', views.farmerinputrequest_list),
    path('kilosahihi/api/farmerinputrequest/<int:pk>/', views.farmerinputrequest_detail),
    path('kilosahihi/api/farmerinputrequest/active', views.farmerinputrequest_list_active),
    path('kilosahihi/api/farminputs', views.farminputs_list),
    path('kilosahihi/api/farminputs/<int:pk>/', views.farminputs_detail),
    path('kilosahihi/api/farminputs/active', views.farminputs_list_active),

    #######################                    REPORTS                            #############################
    path('kilosahihi/api/farmers/transactions/totalcollections/<int:pk>/', views.farmerstransactions_total),
    path('kilosahihi/api/farmers/transactions', views.farmerstransactions_perproduct_perperiod)

]