# Generated by Django 3.1.4 on 2021-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilosahihi', '0003_auto_20210426_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfarmers',
            name='employee_number',
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='farmer_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
