# Generated by Django 3.1.4 on 2021-04-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilosahihi', '0004_auto_20210427_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfarmers',
            name='cooperative',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='kilosahihi.cooperatives'),
            preserve_default=False,
        ),
    ]
