# Generated by Django 3.2.13 on 2022-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilosahihi', '0005_auto_20210428_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfarmers',
            old_name='name',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userfarmers',
            name='username',
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='id_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='member_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='no_of_trees',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userfarmers',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
