# Generated by Django 3.2.13 on 2022-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilosahihi', '0006_auto_20220428_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfarmers',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='member_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='no_of_trees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfarmers',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
