# Generated by Django 3.2.13 on 2022-04-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilosahihi', '0007_auto_20220428_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfarmers',
            name='farmer_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
