# Generated by Django 3.2.13 on 2022-04-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilosahihi', '0008_alter_userfarmers_farmer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfarmers',
            name='user',
        ),
    ]
